// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,participant:10, actor:12, boundary:14, control:16, entity:18, database:20, collections:22, queue:24, class:26, interface:28, abstract:30, enum:32, extends:34, implements:36, as:38, group:40, loop:42, alt:44, else:46, opt:48, par:50, break:52, end:54, note:56, hnote:58, rnote:60, endnote:62, over:64, left:66, right:68, skinparam:70, title:72, header:74, footer:76}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UQVQPOOOOQO'#Dg'#DgOOQO'#Db'#DbO&qQPO'#D`O&xQPO'#C^O'PQPO'#DXO'WQPO'#DZO']QPO'#D^OOQO'#Df'#DfOOQO'#Da'#DaQVQPOOOOQO-E7`-E7`OOQO,59z,59zO'dQPO,58xOOQO,58x,58xO'kQPO,59sOOQO,59s,59sOOQO,59u,59uO'rQPO,59xOOQO,59x,59xOOQO-E7_-E7_OOQO1G.d1G.dOOQO1G/_1G/_OOQO1G/d1G/d",
  stateData: "(T~O!XOS~ORSOSPOTPOUPOVPOWPOXPOYPOZPO[PO]PO^PO_PO`POaPObPOcPOdPOePOfPOgPOhPOiPOjPOkPOlPOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO|TO!OUO!PWO!RVO![XO~OSPOTPOUPOVPOWPOXPOYPOZPO[PO]PO^PO_PO`POaPObPOcPOdPOePOfPOgPOhPOiPOjPOkPOlPOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO~O![[O~P$UO![^O~P$UO![`O~P$UO![aO~O![cO~P$UO![eO~P$UO![fO~P$UO![gO~P$UOR|!R!O!PwSz!P~",
  goto: "#Z![PP!]PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP!]P!]PP!]P!]!a!gPPP!z#OTWOYQYORdYSROYWZR]_bQ]SQ_TRbVTXOYcQORSTVY]_b",
  nodeNames: "⚠ Program StartLine StartMarker Identifier participant actor boundary control entity database collections queue class interface abstract enum extends implements as group loop alt else opt par break end note hnote rnote endnote over left right skinparam title header footer Arrow ColonOp String Other EndLine EndMarker CommentLine LineComment BlockComment PreprocLine PreprocKeyword ContentLine",
  maxTerm: 58,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ",Q~RvXY#iYZ#t]^#ypq#iqr$Rrs$gst%_tu%_uv%_vw%_wx%dxy%_yz%_z{&O{|%_|}%_}!O&a!O!P'X!P!Q'a!Q![%_![!](Z!]!^%_!^!_(`!_!`%_!a!b%_!b!c(u!c!}*[!}#O%_#O#P%_#P#Q%_#Q#R%_#R#S*[#T#c*[#c#d*p#d#o*[#o#p%_#q#r%_#r#s%_~#nQ!X~XY#ipq#i~#yO![~~$OP![~YZ#t~$UQ!c!}$[#T#o$[~$aQ!R~!c!}$[#T#o$[~$jTYZ$g]^$grs$y#O#P$g#Q#R$g~%OTy~YZ$g]^$grs$y#O#P$g#Q#R$g~%dOz~~%iT!O~OY%dZ]%d^;'S%d;'S;=`%x<%lO%d~%{P;=`<%l%d~&RP}!O&U~&XP}!O&[~&aOw~~&dQ}!O&j!`!a&y~&mSz{&[!`!a&y#c#d&[#p#q'R~'OPw~!`!a&[~'UP!`!a&[~'^Pz~!O!P&y~'fPz~wx'i~'lQwx'r#Q#R'i~'uRwx'r!P!Q(O#Q#R'i~(TQ!P~wx'r#Q#R'i~(`Ox~~(cS}!O&U!O!P(o!^!_&O#p#q&O~(rP!O!P&[~(xQ#X#Y)O#g#h)g~)RP#b#c)U~)XP#W#X)[~)aQ|~!c!})[#T#o)[~)jP#h#i)m~)pP#T#U)s~)vP#f#g)y~)|P#h#i*P~*UQR~!c!}*P#T#o*P~*aTS~}!O*[!Q![*[!c!}*[#R#S*[#T#o*[~*uTS~}!O+U!Q![*[!c!}*[#R#S*[#T#o*[~+ZTS~}!O+j!Q![*[!c!}*[#R#S*[#T#o*[~+qTw~S~}!O*[!Q![*[!c!}*[#R#S*[#T#o*[",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 4, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 317
})
